! ===== Rests =====
integer, parameter :: r = 0
integer, parameter :: s = -1
! ===== Dynamics =====
character (LEN=5), parameter :: pppp = "\pppp"
character (LEN=4), parameter :: ppp = "\ppp"
character (LEN=3), parameter :: pp = "\pp"
character (LEN=2), parameter :: p = "\p"
character (LEN=3), parameter :: mp = "\mp"
character (LEN=3), parameter :: mf = "\mf"
character (LEN=2), parameter :: f = "\f"
character (LEN=3), parameter :: ff = "\ff"
character (LEN=4), parameter :: fff = "\fff"
character (LEN=5), parameter :: ffff = "\ffff"
character (LEN=4), parameter :: sfz = "\sfz"
character (LEN=3), parameter :: fp = "\fp"
! ===== Articulations =====
character (LEN=2), parameter :: staccato = "-."
character (LEN=2), parameter :: accent = "->"
character (LEN=2), parameter :: tenuto = "--"
character (LEN=4), parameter :: tenuto_staccato = "-.--"
character (LEN=4), parameter :: tenutoStaccato = "-.--"
character (LEN=2), parameter :: staccatissimo = "-!"
character (LEN=2), parameter :: marcato = "-^"
character (LEN=2), parameter :: stopped = "-+"
character (LEN=4), parameter :: accent_staccato = "->-."
character (LEN=4), parameter :: accentStaccato = "->-."
! ===== Hairpins =====
character (LEN=2), parameter :: cresc = "\<"
character (LEN=2), parameter :: dim = "\>"
character (LEN=2), parameter :: stopHairpin = "\!"
! ===== Slurs =====
character (LEN=1), parameter :: startSlur = "("
character (LEN=1), parameter :: stopSlur = ")"
character (LEN=2), parameter :: stopStartSlur = ")("
! ===== Beam =====
character (LEN=1), parameter :: startBeam = "["
character (LEN=1), parameter :: stopBeam = "]"
! ===== Pedal =====
character (LEN=10), parameter :: sustainOn = "\sustainOn"
character (LEN=11), parameter :: sustainOff = "\sustainOff"
character (LEN=21), parameter :: sustainOffsustainOn = "\sustainOff\sustainOn"
character (LEN=10), parameter :: pedOn = "\sustainOn"
character (LEN=11), parameter :: pedOff = "\sustainOff"
character (LEN=21), parameter :: pedOffpedOn = "\sustainOff\sustainOn"
character (LEN=21), parameter :: pedOffOn = "\sustainOff\sustainOn"
! ===== Grace notes =====
character (LEN=13), parameter :: slashed = "\slashedGrace"
character (LEN=13), parameter :: slashedGrace = "\slashedGrace"
character (LEN=13), parameter :: appoggiatura = "\appoggiatura"
character (LEN=13), parameter :: acciaccatura = "\acciaccatura"
! ===== Durations =====
character (LEN=5), parameter :: d128 = "128  "
character (LEN=5), parameter :: d64 = "64   "
character (LEN=5), parameter :: d64d = "64.  "
character (LEN=5), parameter :: d64dd = "64.. "
character (LEN=5), parameter :: d64ddd = "64..."
character (LEN=5), parameter :: d32 = "32   "
character (LEN=5), parameter :: d32d = "32.  "
character (LEN=5), parameter :: d32dd = "32.. "
character (LEN=5), parameter :: d32ddd = "32..."
character (LEN=5), parameter :: d16 = "16   "
character (LEN=5), parameter :: d16d = "16.  "
character (LEN=5), parameter :: d16dd = "16.. "
character (LEN=5), parameter :: d16ddd = "16..."
character (LEN=5), parameter :: d8 = "8    "
character (LEN=5), parameter :: d8d = "8.   "
character (LEN=5), parameter :: d8dd = "8..  "
character (LEN=5), parameter :: d8ddd = "8... "
character (LEN=5), parameter :: d4 = "4    "
character (LEN=5), parameter :: d4d = "4.   "
character (LEN=5), parameter :: d4dd = "4..  "
character (LEN=5), parameter :: d4ddd = "4... "
character (LEN=5), parameter :: d2 = "2    "
character (LEN=5), parameter :: d2d = "2.   "
character (LEN=5), parameter :: d2dd = "2..  "
character (LEN=5), parameter :: d2ddd = "2... "
character (LEN=5), parameter :: d1 = "1    "
character (LEN=5), parameter :: d1d = "1.   "
character (LEN=5), parameter :: d1dd = "1..  "
character (LEN=5), parameter :: d1ddd = "1... "
