! by David Nalesnik. From: http://lilypond.1069038.n5.nabble.com/Automatic-ottava-handling-td167190i20.html
subroutine SNIPPET_NUMERICOTTAVA()

write(*,"(A)") "numericOttava ="
write(*,"(A)") "#(define-music-function"
write(*,"(A)") "     (parser location number)"
write(*,"(A)") "     (integer?)"
write(*,"(A)") "     (cond"
write(*,"(A)") "          ((equal? number 0)"
write(*,"(A)") "           #{"
write(*,"(A)") "             \ottava #0"
write(*,"(A)") "           #}"
write(*,"(A)") "           )"
write(*,"(A)") "          ((equal? number 1)"
write(*,"(A)") "           #{"
write(*,"(A)") "              \override Staff.OttavaBracket.stencil = #ly:line-spanner::print"
write(*,"(A)") "              \override Staff.OttavaBracket.bound-details ="
write(*,"(A)") "                #`((left . ((Y . 0.0)"
write(*,"(A)") "                            (attach-dir . ,LEFT)"
write(*,"(A)") "                            (padding . 0)"
write(*,"(A)") "                            (stencil-align-dir-y . ,UP)))"
write(*,"(A)") "                   (right . ((Y . 0.0) ; Change the integer here"
write(*,"(A)") "                             (padding . 0)"
write(*,"(A)") "                             (attach-dir . ,RIGHT)"
write(*,"(A)") "                             (text . ,(make-draw-line-markup (cons 0 -0.8))))))"
write(*,"(A)") "              \override Staff.OttavaBracket.left-bound-info ="
write(*,"(A)") "                 #ly:line-spanner::calc-left-bound-info-and-text"
write(*,"(A)") "              \override Staff.OttavaBracket.right-bound-info ="
write(*,"(A)") "                 #ly:line-spanner::calc-right-bound-info"
write(*,"(A)") "              \ottava #number"
write(*,"(A)") '              \set Staff.ottavation ="8"'
write(*,"(A)") "           #}"
write(*,"(A)") "           )"
write(*,"(A)") "          ((equal? number 2)"
write(*,"(A)") "           #{"
write(*,"(A)") "              \override Staff.OttavaBracket.stencil = #ly:line-spanner::print"
write(*,"(A)") "              \override Staff.OttavaBracket.bound-details ="
write(*,"(A)") "                #`((left . ((Y . 0.0)"
write(*,"(A)") "                            (attach-dir . ,LEFT)"
write(*,"(A)") "                            (padding . 0)"
write(*,"(A)") "                            (stencil-align-dir-y . ,UP)))"
write(*,"(A)") "                   (right . ((Y . 0.0) ; Change the integer here"
write(*,"(A)") "                             (padding . 0)"
write(*,"(A)") "                             (attach-dir . ,RIGHT)"
write(*,"(A)") "                             (text . ,(make-draw-line-markup (cons 0 -0.8))))))"
write(*,"(A)") "              \override Staff.OttavaBracket.left-bound-info ="
write(*,"(A)") "                 #ly:line-spanner::calc-left-bound-info-and-text"
write(*,"(A)") "              \override Staff.OttavaBracket.right-bound-info ="
write(*,"(A)") "                 #ly:line-spanner::calc-right-bound-info"
write(*,"(A)") "              \ottava #number"
write(*,"(A)") '              \set Staff.ottavation = \markup\concat{"15" \teeny""}'
write(*,"(A)") "           #}"
write(*,"(A)") "           )"
write(*,"(A)") "          ((equal? number -1)"
write(*,"(A)") "           #{"
write(*,"(A)") "              \override Staff.OttavaBracket.stencil = #ly:line-spanner::print"
write(*,"(A)") "              \override Staff.OttavaBracket.bound-details ="
write(*,"(A)") "                #`((left . ((Y . 0.0)"
write(*,"(A)") "                            (attach-dir . ,LEFT)"
write(*,"(A)") "                            (padding . 0)"
write(*,"(A)") "                            (stencil-align-dir-y . ,DOWN)))"
write(*,"(A)") "                   (right . ((Y . 0.0) ; Change the integer here"
write(*,"(A)") "                             (padding . 0)"
write(*,"(A)") "                             (attach-dir . ,RIGHT)"
write(*,"(A)") "                             (text . ,(make-draw-line-markup (cons 0 0.8))))))"
write(*,"(A)") "              \override Staff.OttavaBracket.left-bound-info ="
write(*,"(A)") "                 #ly:line-spanner::calc-left-bound-info-and-text"
write(*,"(A)") "              \override Staff.OttavaBracket.right-bound-info ="
write(*,"(A)") "                 #ly:line-spanner::calc-right-bound-info"
write(*,"(A)") "              \ottava #number"
write(*,"(A)") '              \set Staff.ottavation ="8"'
write(*,"(A)") "           #}"
write(*,"(A)") "           )"
write(*,"(A)") "          ((equal? number -2)"
write(*,"(A)") "           #{"
write(*,"(A)") "              \override Staff.OttavaBracket.stencil = #ly:line-spanner::print"
write(*,"(A)") "              \override Staff.OttavaBracket.bound-details ="
write(*,"(A)") "                #`((left . ((Y . 0.0)"
write(*,"(A)") "                            (attach-dir . ,LEFT)"
write(*,"(A)") "                            (padding . 0)"
write(*,"(A)") "                            (stencil-align-dir-y . ,DOWN)))"
write(*,"(A)") "                   (right . ((Y . 0.0) ; Change the integer here"
write(*,"(A)") "                             (padding . 0)"
write(*,"(A)") "                             (attach-dir . ,RIGHT)"
write(*,"(A)") "                             (text . ,(make-draw-line-markup (cons 0 0.8))))))"
write(*,"(A)") "              \override Staff.OttavaBracket.left-bound-info ="
write(*,"(A)") "                 #ly:line-spanner::calc-left-bound-info-and-text"
write(*,"(A)") "              \override Staff.OttavaBracket.right-bound-info ="
write(*,"(A)") "                 #ly:line-spanner::calc-right-bound-info"
write(*,"(A)") "              \ottava #number"
write(*,"(A)") '              \set Staff.ottavation ="15"'
write(*,"(A)") "           #}"
write(*,"(A)") "           )))"

write(11,"(A)") "numericOttava ="
write(11,"(A)") "#(define-music-function"
write(11,"(A)") "     (parser location number)"
write(11,"(A)") "     (integer?)"
write(11,"(A)") "     (cond"
write(11,"(A)") "          ((equal? number 0)"
write(11,"(A)") "           #{"
write(11,"(A)") "             \ottava #0"
write(11,"(A)") "           #}"
write(11,"(A)") "           )"
write(11,"(A)") "          ((equal? number 1)"
write(11,"(A)") "           #{"
write(11,"(A)") "              \override Staff.OttavaBracket.stencil = #ly:line-spanner::print"
write(11,"(A)") "              \override Staff.OttavaBracket.bound-details ="
write(11,"(A)") "                #`((left . ((Y . 0.0)"
write(11,"(A)") "                            (attach-dir . ,LEFT)"
write(11,"(A)") "                            (padding . 0)"
write(11,"(A)") "                            (stencil-align-dir-y . ,UP)))"
write(11,"(A)") "                   (right . ((Y . 0.0) ; Change the integer here"
write(11,"(A)") "                             (padding . 0)"
write(11,"(A)") "                             (attach-dir . ,RIGHT)"
write(11,"(A)") "                             (text . ,(make-draw-line-markup (cons 0 -0.8))))))"
write(11,"(A)") "              \override Staff.OttavaBracket.left-bound-info ="
write(11,"(A)") "                 #ly:line-spanner::calc-left-bound-info-and-text"
write(11,"(A)") "              \override Staff.OttavaBracket.right-bound-info ="
write(11,"(A)") "                 #ly:line-spanner::calc-right-bound-info"
write(11,"(A)") "              \ottava #number"
write(11,"(A)") '              \set Staff.ottavation ="8"'
write(11,"(A)") "           #}"
write(11,"(A)") "           )"
write(11,"(A)") "          ((equal? number 2)"
write(11,"(A)") "           #{"
write(11,"(A)") "              \override Staff.OttavaBracket.stencil = #ly:line-spanner::print"
write(11,"(A)") "              \override Staff.OttavaBracket.bound-details ="
write(11,"(A)") "                #`((left . ((Y . 0.0)"
write(11,"(A)") "                            (attach-dir . ,LEFT)"
write(11,"(A)") "                            (padding . 0)"
write(11,"(A)") "                            (stencil-align-dir-y . ,UP)))"
write(11,"(A)") "                   (right . ((Y . 0.0) ; Change the integer here"
write(11,"(A)") "                             (padding . 0)"
write(11,"(A)") "                             (attach-dir . ,RIGHT)"
write(11,"(A)") "                             (text . ,(make-draw-line-markup (cons 0 -0.8))))))"
write(11,"(A)") "              \override Staff.OttavaBracket.left-bound-info ="
write(11,"(A)") "                 #ly:line-spanner::calc-left-bound-info-and-text"
write(11,"(A)") "              \override Staff.OttavaBracket.right-bound-info ="
write(11,"(A)") "                 #ly:line-spanner::calc-right-bound-info"
write(11,"(A)") "              \ottava #number"
write(11,"(A)") '              \set Staff.ottavation = \markup\concat{"15" \teeny""}'
write(11,"(A)") "           #}"
write(11,"(A)") "           )"
write(11,"(A)") "          ((equal? number -1)"
write(11,"(A)") "           #{"
write(11,"(A)") "              \override Staff.OttavaBracket.stencil = #ly:line-spanner::print"
write(11,"(A)") "              \override Staff.OttavaBracket.bound-details ="
write(11,"(A)") "                #`((left . ((Y . 0.0)"
write(11,"(A)") "                            (attach-dir . ,LEFT)"
write(11,"(A)") "                            (padding . 0)"
write(11,"(A)") "                            (stencil-align-dir-y . ,DOWN)))"
write(11,"(A)") "                   (right . ((Y . 0.0) ; Change the integer here"
write(11,"(A)") "                             (padding . 0)"
write(11,"(A)") "                             (attach-dir . ,RIGHT)"
write(11,"(A)") "                             (text . ,(make-draw-line-markup (cons 0 0.8))))))"
write(11,"(A)") "              \override Staff.OttavaBracket.left-bound-info ="
write(11,"(A)") "                 #ly:line-spanner::calc-left-bound-info-and-text"
write(11,"(A)") "              \override Staff.OttavaBracket.right-bound-info ="
write(11,"(A)") "                 #ly:line-spanner::calc-right-bound-info"
write(11,"(A)") "              \ottava #number"
write(11,"(A)") '              \set Staff.ottavation ="8"'
write(11,"(A)") "           #}"
write(11,"(A)") "           )"
write(11,"(A)") "          ((equal? number -2)"
write(11,"(A)") "           #{"
write(11,"(A)") "              \override Staff.OttavaBracket.stencil = #ly:line-spanner::print"
write(11,"(A)") "              \override Staff.OttavaBracket.bound-details ="
write(11,"(A)") "                #`((left . ((Y . 0.0)"
write(11,"(A)") "                            (attach-dir . ,LEFT)"
write(11,"(A)") "                            (padding . 0)"
write(11,"(A)") "                            (stencil-align-dir-y . ,DOWN)))"
write(11,"(A)") "                   (right . ((Y . 0.0) ; Change the integer here"
write(11,"(A)") "                             (padding . 0)"
write(11,"(A)") "                             (attach-dir . ,RIGHT)"
write(11,"(A)") "                             (text . ,(make-draw-line-markup (cons 0 0.8))))))"
write(11,"(A)") "              \override Staff.OttavaBracket.left-bound-info ="
write(11,"(A)") "                 #ly:line-spanner::calc-left-bound-info-and-text"
write(11,"(A)") "              \override Staff.OttavaBracket.right-bound-info ="
write(11,"(A)") "                 #ly:line-spanner::calc-right-bound-info"
write(11,"(A)") "              \ottava #number"
write(11,"(A)") '              \set Staff.ottavation ="15"'
write(11,"(A)") "           #}"
write(11,"(A)") "           )))"

end subroutine SNIPPET_NUMERICOTTAVA
