subroutine SNIPPET_CROSS_STAFF_ARPEGGIOS()

write(*,"(A)") "connectArpeggioArrowUp = {"
write(*,"(A)") "  \override Score.Arpeggio.arpeggio-direction = #UP"
write(*,"(A)") "}"
write(*,"(A)") "connectArpeggioArrowDown = {"
write(*,"(A)") "  \override Score.Arpeggio.arpeggio-direction = #DOWN"
write(*,"(A)") "}"
write(*,"(A)") "connectArpeggioNormal = {"
write(*,"(A)") "  \revert Score.Arpeggio.stencil"
write(*,"(A)") "  \revert Score.Arpeggio.arpeggio-direction"
write(*,"(A)") "}"
write(*,"(A)") "connectArpeggioBracket = {"
write(*,"(A)") "  \override Score.Arpeggio.stencil = #ly:arpeggio::brew-chord-bracket"
write(*,"(A)") "}"

write(11,"(A)") "connectArpeggioArrowUp = {"
write(11,"(A)") "  \override Score.Arpeggio.arpeggio-direction = #UP"
write(11,"(A)") "}"
write(11,"(A)") "connectArpeggioArrowDown = {"
write(11,"(A)") "  \override Score.Arpeggio.arpeggio-direction = #DOWN"
write(11,"(A)") "}"
write(11,"(A)") "connectArpeggioNormal = {"
write(11,"(A)") "  \revert Score.Arpeggio.stencil"
write(11,"(A)") "  \revert Score.Arpeggio.arpeggio-direction"
write(11,"(A)") "}"
write(11,"(A)") "connectArpeggioBracket = {"
write(11,"(A)") "  \override Score.Arpeggio.stencil = #ly:arpeggio::brew-chord-bracket"
write(11,"(A)") "}"

end subroutine SNIPPET_CROSS_STAFF_ARPEGGIOS
