subroutine SNIPPET_LIVEELECTRONICS()

write(*,"(A)") "LE = #(define-event-function"
write(*,"(A)") "     (parser location text hshift description)"
write(*,"(A)") "     (string? number? string?)"
write(*,"(A)") "      #{"
write(*,"(A)") "        -\markup {" 
write(*,"(A)") "          \hspace #hshift"
write(*,"(A)") "          \center-column {"
write(*,"(A)") "            \combine"
write(*,"(A)") "            \arrow-head #Y #UP ##t"
write(*,"(A)") "            \draw-line #'(0 . -3)"
write(*,"(A)") "            \hspace #-2 \raise #999 \circle $text"
write(*,"(A)") "          }"
write(*,"(A)") "          \raise #-6 $description"
write(*,"(A)") "        }"
write(*,"(A)") "#}"
write(*,"(A)") "       )"

write(11,"(A)") "LE = #(define-event-function"
write(11,"(A)") "     (parser location text hshift description)"
write(11,"(A)") "     (string? number? string?)"
write(11,"(A)") "      #{"
write(11,"(A)") "        -\markup {" 
write(11,"(A)") "          \hspace #hshift"
write(11,"(A)") "          \center-column {"
write(11,"(A)") "            \combine"
write(11,"(A)") "            \arrow-head #Y #UP ##t"
write(11,"(A)") "            \draw-line #'(0 . -3)"
write(11,"(A)") "            \hspace #-2 \raise #999 \circle $text"
write(11,"(A)") "          }"
write(11,"(A)") "          \raise #-6 $description"
write(11,"(A)") "        }"
write(11,"(A)") "#}"
write(11,"(A)") "       )"

end subroutine SNIPPET_LIVEELECTRONICS
